export const COMMON_VALUES = {
    MR_APPROVAL_STATUS_APPROVED: 'APPROVED',
    MR_APPROVAL_STATUS_PENDING: 'PENDING',
    MR_APPROVAL_STATUS_REJECTED: 'REJECTED',

    MOTOR_GUARD_PRODUCT_CODE: '1',
    MOTOR_GUARD_EXTRA_PRODUCT_CODE: '2',
    THIRD_PARTY_PRODUCT_CODE: '3',

    MOTOR_CAR_RISK_TYPE: '1',
    MOTOR_GUARD_EXTRA_MAX_YEARS:'7',

    MINIMUM_TOWING_CHARGE:'2500',
    MINIMUM_PAB_CHARGE:'15000',
    MAXIMUM_PAB_CHARGE:'500000',


    IJARAH_LEASING_TYPE_CODE:'3',

    UP_FRONT_NCB_1_YEAR_ID:'20',
    UP_FRONT_NCB_1_YEAR_VALUE:'1 Year'

};